#
# Build stage
#
FROM maven:3.6-jdk-8-slim AS build
COPY src /build/src
COPY pom.xml /build/
RUN mvn -f /build/pom.xml clean package -DskipTests

#
# Package stage
#
FROM openjdk:8-alpine
COPY --from=build /build/target/trading-1.0-SNAPSHOT.jar D:\Jarvis Coding\jarvis_data_eng_ShubhkarmanSandhu\springboot\target\trading-1.0-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","D:\Jarvis Coding\jarvis_data_eng_ShubhkarmanSandhu\springboot\target\trading-1.0-SNAPSHOT.jar"]